# ./home/bash/bash.nix
{
  lib,
  config,
  ...
}: {
  # Import modules for tools that will be integrated into the shell.
  imports = [
    ../utils/starship.nix # Starship config is shell-agnostic, we can reuse it.
    ../utils/atuin.nix
    ../../modules/home-manager/shell/scripts.nix
  ];

  # All program configurations are grouped under a single 'programs' attribute set.
  programs = {
    bash = {
      enable = true;

      # --- Quality of Life Features ---
      enableCompletion = true;
      enableVteIntegration = true;

      # --- History Settings ---
      historyControl = ["ignoredups" "erasedups"];
      historySize = 10000;
      historyFileSize = 10000;

      # --- Aliases ---
      shellAliases = (import ../../modules/home-manager/shell/aliases.nix {inherit lib config;}).sh;

      # --- Custom Scripts and Initialization ---
      initExtra = ''
        # Use the green Starship theme for bash (generated by starship.nix)
        export STARSHIP_CONFIG="${config.home.homeDirectory}/.config/starship-bash.toml"

        # Define the flake path variable for our functions.
        export _RELOAD_FLAKE_PATH="${config.home.homeDirectory}/nixosconfig#"

        # Source our custom functions file.
        source ${../zsh/my_functions.sh}
        source ${../zsh/copycr.sh}
      '';
    };

    # --- Program Integrations ---
    starship.enableBashIntegration = true;
    zoxide = {
      enable = true;
      enableBashIntegration = true;
    };
    atuin = {
      # Configuration is in the imported atuin.nix
      enableBashIntegration = true;
    };
  };
}
