version: "3.8"

services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
      # Optional: Define the label autoheal looks for.
      # 'all' or leaving it unset defaults to monitoring containers with label `autoheal=true`.
      - AUTOHEAL_CONTAINER_LABEL=all
      # Optional: Set loop interval (default 5 seconds)
      - AUTOHEAL_INTERVAL=30
      # Optional: Stop timeout before sending SIGKILL (default 10 seconds)
      - AUTOHEAL_STOP_TIMEOUT=10
    volumes:
      # REQUIRED: Mount the docker socket so autoheal can interact with docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Hectic way that gemini wants us to inherit our timezone
      - /etc/localtime:/etc/localtime:ro # <---- Add this line (read-only is good practice)
    environment:
      # TZ variable is not needed if mounting /etc/localtime
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      # - WATCHTOWER_REVIVE_STOPPED=true # Uncomment if you want stopped containers to start after update
      - WATCHTOWER_SCHEDULE=0 0 3 * * * # Runs daily at 3:00 AM according to host time
    restart: unless-stopped

  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    restart: unless-stopped
    # This is the crucial part that runs Dozzle in agent mode
    command: agent
    environment:
      # This gives your remote host a friendly name in the Dozzle UI
      - DOZZLE_HOSTNAME=igpu
    ports:
      # Exposes the agent on port 7007. Ensure this port is not in use.
      - "7007:7007"
    volumes:
      # Mount the Docker socket (read-only is best practice for agents)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # healthcheck:
    #   test: ["CMD", "/dozzle", "healthcheck"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
