version: "3.8"

services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth
      # Optional: Define the label autoheal looks for.
      # 'all' or leaving it unset defaults to monitoring containers with label `autoheal=true`.
      - AUTOHEAL_CONTAINER_LABEL=all
      # Optional: Set loop interval (default 5 seconds)
      - AUTOHEAL_INTERVAL=30
      # Optional: Stop timeout before sending SIGKILL (default 10 seconds)
      - AUTOHEAL_STOP_TIMEOUT=10
    volumes:
      # REQUIRED: Mount the docker socket so autoheal can interact with docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Hectic way that gemini wants us to inherit our timezone
      - /etc/localtime:/etc/localtime:ro # <---- Add this line (read-only is good practice)
    environment:
      # TZ variable is not needed if mounting /etc/localtime
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      # - WATCHTOWER_REVIVE_STOPPED=true # Uncomment if you want stopped containers to start after update
      - WATCHTOWER_SCHEDULE=0 0 3 * * * # Runs daily at 3:00 AM according to host time
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker/dozzle/data:/data
    ports:
      - 8082:8080
    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_REMOTE_AGENT=100.72.14.81:7007,192.168.1.33:7007
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
