# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # Group all boot-related options under a single attribute set to avoid repetition.
  boot = {
    initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
    initrd.kernelModules = ["virtio_scsi"];
    kernelModules = [];
    extraModulePackages = [];
  };

  # fileSystems."/" =
  #   {
  #     device = "/dev/disk/by-uuid/610d34fd-49d9-42df-a7ec-4e7576d8b0ee";
  #     fsType = "ext4";
  #   };
  #
  # fileSystems."/boot" =
  #   {
  #     device = "/dev/disk/by-uuid/9A13-F8E0";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  # 24 GiB swapfile on the ext4 root. doc1 is balloonable and its 2026-09-02
  # rolling update exhausted the previous 16 GiB while nix-daemon reached
  # ~19.7 GiB RSS. This is bounded emergency capacity, not permission to hide
  # recurring daemon growth behind unlimited swap. Disk swap survives a balloon
  # squeeze; zram would only compress RAM the balloon is reclaiming. See
  # Forgejo #12 (fleet RAM audit).
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 24 * 1024; # 24 GiB in MiB
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
