version: "3.8"

services:
  # 1️⃣ Network namespace anchor (shared with tailscale & caddy)
  network-holder:
    image: k8s.gcr.io/pause:3.9
    container_name: invoices_network_holder
    hostname: invoices
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 2️⃣ Tailscale sidecar (shares netns with network-holder)
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-invoices
    network_mode: service:network-holder
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=invoices
    volumes:
      - /mnt/docker/invoices/ts-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    # healthcheck:
    #   test: tailscale status --peers=false --json | grep -q '"Online":true'
    depends_on:
      - network-holder

  # 3️⃣ Caddy (shares netns; serves Docspell via invoices.ablz.au)
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy-invoices
    network_mode: service:network-holder
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/docker/invoices/caddy_data:/data
      - /mnt/docker/invoices/caddy_config:/config
    restart: unless-stopped
    depends_on:
      tailscale:
        condition: service_started
      network-holder:
        condition: service_started
      docspell-restserver:
        condition: service_started

  # 4️⃣ Docspell REST server (UI/API)
  docspell-restserver:
    image: ghcr.io/docspell/restserver:latest
    hostname: docspell-restserver
    container_name: docspell-restserver
    restart: unless-stopped
    environment:
      TZ: "Australia/Perth"
      DOCSPELL_SERVER_INTERNAL__URL: "http://docspell-restserver:7880"
      DOCSPELL_SERVER_BIND_ADDRESS: "0.0.0.0"

      # Secrets/policy
      DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET: ${DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET}
      DOCSPELL_SERVER_AUTH_SERVER__SECRET: ${DOCSPELL_SERVER_AUTH_SERVER__SECRET}
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED: "true"
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED: "true"
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE: ${DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE}
      DOCSPELL_SERVER_BACKEND_SIGNUP_MODE: ${DOCSPELL_SERVER_BACKEND_SIGNUP_MODE:-invite}
      DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD: ${DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD}

      # DB & Solr
      DOCSPELL_SERVER_BACKEND_JDBC_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      DOCSPELL_SERVER_BACKEND_JDBC_USER: ${POSTGRES_USER}
      DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
      DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL: "http://docspell-solr:8983/solr/docspell"
      DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED: "false"
    depends_on:
      db:
        condition: service_started
      docspell-solr:
        condition: service_started

  # 5️⃣ Docspell worker
  docspell-joex:
    image: ghcr.io/docspell/joex:latest
    hostname: docspell-joex
    container_name: docspell-joex
    restart: unless-stopped
    environment:
      TZ: "Australia/Perth"
      DOCSPELL_JOEX_APP__ID: "joex1"
      DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME: "joex1"
      DOCSPELL_JOEX_SCHEDULER_NAME: "joex1"
      DOCSPELL_JOEX_BASE__URL: "http://docspell-joex:7878"
      DOCSPELL_JOEX_BIND_ADDRESS: "0.0.0.0"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: "http://docspell-solr:8983/solr/docspell"
      DOCSPELL_JOEX_JDBC_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      DOCSPELL_JOEX_JDBC_USER: ${POSTGRES_USER}
      DOCSPELL_JOEX_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
      DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER: "docker,trivial"
    depends_on:
      db:
        condition: service_started
      docspell-solr:
        condition: service_started

  # 6️⃣ Drop files here to auto-ingest
  docspell-consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:${DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE}"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /mnt/docker/invoices/docspell/inbox:/opt/docs
    depends_on:
      docspell-restserver:
        condition: service_started

  # 7️⃣ Postgres (persistent data under /mnt/docker/invoices)
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /mnt/docker/invoices/postgres/data:/var/lib/postgresql/data

  # 8️⃣ Solr core
  docspell-solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - /mnt/docker/invoices/solr/data:/var/solr
    command:
      - bash
      - -c
      - "precreate-core docspell; exec solr -f -Dsolr.modules=analysis-extras"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s
