#!/usr/bin/env bash
set -e # Stop on error

# 1. FIND REPO ROOT
# -----------------------------
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

echo "📂 Working in Repo Root: $REPO_ROOT"

# 2. CONFIGURATION
# -----------------------------
PRIVATE_KEY_SOURCE="$HOME/.ssh/id_ed25519"
PUBLIC_KEY_SOURCE="$HOME/.ssh/id_ed25519.pub"
AUTHORIZED_KEYS_SOURCE="$REPO_ROOT/home/ssh/authorized_keys"

# Destinations (Relative to Repo Root)
SECRETS_DIR="$REPO_ROOT/secrets/secrets"
PRIVATE_KEY_DEST="$SECRETS_DIR/ssh_key_abl030"
PUBLIC_KEYS_NIX="$REPO_ROOT/hosts/common/user_keys.nix"

# 3. CHECK IDENTITY (BOOTSTRAP)
# -----------------------------
if [ ! -f "$PRIVATE_KEY_SOURCE" ]; then
    echo "⚠️  No SSH key found at $PRIVATE_KEY_SOURCE"
    # This shouldn't happen now since you generated it, but good to keep
    read -p "❓ Do you want to generate a NEW Master Fleet Keypair here? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        mkdir -p "$HOME/.ssh"
        ssh-keygen -t ed25519 -C "master-fleet-identity" -f "$PRIVATE_KEY_SOURCE" -N ""
        echo "✅ Generated new keypair."
    else
        echo "❌ Migration aborted."
        exit 1
    fi
fi

# 4. ENCRYPT PRIVATE KEY (SOPS)
# -----------------------------
echo "🔒 Encrypting Master Private Key into Sops..."
cp "$PRIVATE_KEY_SOURCE" "$PRIVATE_KEY_DEST"

# FIX: Switch to the directory where .sops.yaml lives
if [ -d "$REPO_ROOT/secrets" ]; then
    cd "$REPO_ROOT/secrets"
else
    echo "❌ Could not find secrets directory at $REPO_ROOT/secrets"
    exit 1
fi

# Sops will now find .sops.yaml in the current directory (.)
# It handles the absolute path in PRIVATE_KEY_DEST by calculating the relative path
sops --encrypt --in-place "$PRIVATE_KEY_DEST"

echo "✅ Private key encrypted to secrets/secrets/ssh_key_abl030"

# Return to root for the rest
cd "$REPO_ROOT"

# 5. GENERATE TRUST LIST
# -----------------------------
echo "🔑 Generating Global Trust List..."

cat > "$PUBLIC_KEYS_NIX" <<EOF
{ ... }:
{
  # GLOBAL TRUST LIST
  # Auto-generated by scripts/migrate_ssh.sh
  users.users.abl030.openssh.authorizedKeys.keys = [
EOF

# Add Master Key
if [ -f "$PUBLIC_KEY_SOURCE" ]; then
    PUB_KEY=$(cat "$PUBLIC_KEY_SOURCE")
    echo "    # Master Fleet Identity" >> "$PUBLIC_KEYS_NIX"
    echo "    \"$PUB_KEY\"" >> "$PUBLIC_KEYS_NIX"
fi

# Add existing authorized keys
if [ -f "$AUTHORIZED_KEYS_SOURCE" ]; then
    echo "    # Manual Keys (from home/ssh/authorized_keys)" >> "$PUBLIC_KEYS_NIX"
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^#.*$ ]] && continue
        [[ -z "$line" ]] && continue
        # Avoid duplicates
        if [[ "$line" != "$PUB_KEY" ]]; then
             echo "    \"$line\"" >> "$PUBLIC_KEYS_NIX"
        fi
    done < "$AUTHORIZED_KEYS_SOURCE"
fi

echo "  ];" >> "$PUBLIC_KEYS_NIX"
echo "}" >> "$PUBLIC_KEYS_NIX"

echo "✅ Generated hosts/common/user_keys.nix"
echo "🚀 DONE! Don't forget to 'git add' the new files."
