_: {
  # GLOBAL TRUST LIST
  # Auto-generated by scripts/migrate_ssh.sh
  users.users.abl030.openssh.authorizedKeys.keys = [
    # Master Fleet Identity
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDGR7mbMKs8alVN4K1ynvqT5K3KcXdeqlV77QQS0K1qy master-fleet-identity"
    # Manual Keys (from home/ssh/authorized_keys)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9aE9VRI+2to5Iy04f/MvPfbs6E5q0xTjnErPC4pEjR cullenwines\andy.b@CW-PC001"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJnFw/zW4X+1pV2yWXQwaFtZ23K5qquglAEmbbqvLe5g root@pihole"
  ];
}
