CREATE DATABASE IF NOT EXISTS `Ombi`;
CREATE DATABASE IF NOT EXISTS `Ombi_Settings`;
CREATE DATABASE IF NOT EXISTS `Ombi_External`;

GRANT ALL PRIVILEGES ON `Ombi`.* TO 'ombi'@'%';
GRANT ALL PRIVILEGES ON `Ombi_Settings`.* TO 'ombi'@'%';
GRANT ALL PRIVILEGES ON `Ombi_External`.* TO 'ombi'@'%';

FLUSH PRIVILEGES;
