name: "Build and Cache NixOS/HM (no all-hosts)"

on:
  push:
    branches: [master] # ← was main
  pull_request:
    branches: [master] # ← was main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-cache:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixosconfig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build + push nixosConfigurations and homeConfigurations
        shell: bash
        run: |
          set -euo pipefail
          if command -v sudo >/dev/null; then SUDO=sudo; else SUDO=; fi

          # Prefer system gcroots; fall back to per-user if needed.
          ROOT_BASE="/nix/var/nix/gcroots/nix-serve"
          if ! $SUDO install -d -m 0755 "$ROOT_BASE"; then
            ROOT_BASE="$HOME/.cache/nix-serve-gcroots"
            mkdir -p "$ROOT_BASE"
            echo "Using per-user GC roots at $ROOT_BASE"
          fi

          push_closure() {
            local path="$1"
            nix path-info -r "$path" | xargs -r -n 128 cachix push nixosconfig
          }

          keep_latest_root() {
            local tag="$1" out="$2" root="$ROOT_BASE/${tag}-latest"
            ln -sfn "$out" "$root"
            $SUDO nix-store --add-root "$root" --indirect "$out"
          }

          HOSTS_RAW="$(nix eval --raw .#nixosConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          HOMES_RAW="$(nix eval --raw .#homeConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          if [[ -z "${HOSTS_RAW}${HOMES_RAW}" ]]; then
            echo "Error: flake exports neither nixosConfigurations nor homeConfigurations."
            exit 1
          fi

          if [[ -n "${HOSTS_RAW}" ]]; then
            readarray -t HOSTS <<< "${HOSTS_RAW}"
            echo "Discovered nixosConfigurations:"
            for h in "${HOSTS[@]}"; do echo "  - ${h}"; done
            for h in "${HOSTS[@]}"; do
              echo "::group::nixosConfigurations.${h}"
              out="$(nix build --accept-flake-config --no-link --print-out-paths \
                ".#nixosConfigurations.${h}.config.system.build.toplevel")"
              push_closure "$out"
              keep_latest_root "nixos-${h}" "$out"
              cachix pin nixosconfig "nixos-${h}" "$out" --keep-days 7
              echo "::endgroup::"
            done
          else
            echo "No nixosConfigurations exported by flake."
          fi

          if [[ -n "${HOMES_RAW}" ]]; then
            readarray -t HOMES <<< "${HOMES_RAW}"
            echo "Discovered homeConfigurations:"
            for u in "${HOMES[@]}"; do echo "  - ${u}"; done
            for u in "${HOMES[@]}"; do
              echo "::group::homeConfigurations.${u}"
              out="$(nix build --accept-flake-config --no-link --print-out-paths \
                ".#homeConfigurations.${u}.activationPackage")"
              push_closure "$out"
              keep_latest_root "hm-${u}" "$out"
              cachix pin nixosconfig "hm-${u}" "$out" --keep-days 7
              echo "::endgroup::"
            done
          else
            echo "No homeConfigurations exported by flake."
          fi

          # Clean up (system-wide if sudo available; otherwise per-user GC still helps)
          $SUDO nix-collect-garbage --delete-old || true
          $SUDO nix-store --optimise || true
