name: "Build and Cache NixOS/HM (no all-hosts)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            # If any inputs are private GitHub repos:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixosconfig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build + push nixosConfigurations and homeConfigurations
        shell: bash
        run: |
          set -euo pipefail

          # Enumerate attr names **without** jq and **without** getFlake.
          # If an attr set is missing, swallow the error and leave RAW empty.
          HOSTS_RAW="$(nix eval --raw .#nixosConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          HOMES_RAW="$(nix eval --raw .#homeConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          # Hard fail if neither is exported.
          if [[ -z "${HOSTS_RAW}${HOMES_RAW}" ]]; then
            echo "Error: flake exports neither nixosConfigurations nor homeConfigurations."
            exit 1
          fi

          # Build + push all NixOS hosts.
          if [[ -n "${HOSTS_RAW}" ]]; then
            readarray -t HOSTS <<< "${HOSTS_RAW}"
            echo "Discovered nixosConfigurations:"
            for h in "${HOSTS[@]}"; do echo "  - ${h}"; done

            for h in "${HOSTS[@]}"; do
              echo "::group::nixosConfigurations.${h}"
              out="$(nix build \
                --accept-flake-config \
                --no-link \
                --print-out-paths \
                ".#nixosConfigurations.${h}.config.system.build.toplevel")"
              nix copy --to "cachix://nixosconfig" "$out"
              echo "::endgroup::"
            done
          else
            echo "No nixosConfigurations exported by flake."
          fi

          # Build + push all Home Manager configs.
          if [[ -n "${HOMES_RAW}" ]]; then
            readarray -t HOMES <<< "${HOMES_RAW}"
            echo "Discovered homeConfigurations:"
            for u in "${HOMES[@]}"; do echo "  - ${u}"; done

            for u in "${HOMES[@]}"; do
              echo "::group::homeConfigurations.${u}"
              out="$(nix build \
                --accept-flake-config \
                --no-link \
                --print-out-paths \
                ".#homeConfigurations.${u}.activationPackage")"
              nix copy --to "cachix://nixosconfig" "$out"
              echo "::endgroup::"
            done
          else
            echo "No homeConfigurations exported by flake."
          fi
