name: "Build and Cache NixOS/HM (no all-hosts)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            # Helps if any inputs are private Git repos:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixosconfig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build + push all nixosConfigurations
        shell: bash
        run: |
          set -euo pipefail
          HOSTS_RAW="$(nix eval --raw --expr 'let f = builtins.getFlake "."; in builtins.concatStringsSep "\n" (builtins.attrNames (f.nixosConfigurations or {}))' || true)"
          if [[ -z "${HOSTS_RAW// }" ]]; then
            echo "No nixosConfigurations found; skipping."
          else
            readarray -t HOSTS <<< "$HOSTS_RAW"
            for h in "${HOSTS[@]}"; do
              echo "::group::nixosConfigurations.${h}"
              out="$(nix build --no-link --print-out-paths ".#nixosConfigurations.${h}.config.system.build.toplevel")"
              nix copy --to "cachix://nixosconfig" "$out"
              echo "::endgroup::"
            done
          fi

      - name: Build + push all homeConfigurations (if any)
        shell: bash
        run: |
          set -euo pipefail
          HOMES_RAW="$(nix eval --raw --expr 'let f = builtins.getFlake "."; in builtins.concatStringsSep "\n" (builtins.attrNames (f.homeConfigurations or {}))' || true)"
          if [[ -z "${HOMES_RAW// }" ]]; then
            echo "No homeConfigurations found; skipping."
          else
            readarray -t HOMES <<< "$HOMES_RAW"
            for u in "${HOMES[@]}"; do
              echo "::group::homeConfigurations.${u}"
              out="$(nix build --no-link --print-out-paths ".#homeConfigurations.${u}.activationPackage")"
              nix copy --to "cachix://nixosconfig" "$out"
              echo "::endgroup::"
            done
          fi
