name: "Build and Cache NixOS/HM (no all-hosts)"

on:
  # Run once for pushes to master
  push:
    branches: [master]
  # Run for PRs targeting master (branch pushes won't trigger)
  pull_request:
    branches: [master]
  workflow_dispatch:

# Ensure only one run per PR or ref; cancel older in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-cache:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            # If any inputs are private GitHub repos:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nixosconfig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build + push nixosConfigurations and homeConfigurations
        shell: bash
        run: |
          set -euo pipefail

          # Per-user GC roots only; we do NOT use sudo anywhere.
          ROOT_BASE="$HOME/.cache/nix-serve-gcroots"
          mkdir -p "$ROOT_BASE"

          # Push the full closure of a store path to Cachix (chunked to avoid long argv)
          push_closure() {
            local path="$1"
            nix path-info -r "$path" | xargs -r -n 128 cachix push nixosconfig
          }

          # Keep exactly the latest build rooted per tag; older outputs become unrooted and GC'able
          keep_latest_root() {
            local tag="$1" out="$2"
            ln -sfn "$out" "$ROOT_BASE/${tag}-latest"
          }

          # Enumerate exported attrs without jq/getFlake
          HOSTS_RAW="$(nix eval --raw .#nixosConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          HOMES_RAW="$(nix eval --raw .#homeConfigurations \
            --apply 'x: builtins.concatStringsSep "\n" (builtins.attrNames x)' \
            2>/dev/null || echo "")"

          if [[ -z "${HOSTS_RAW}${HOMES_RAW}" ]]; then
            echo "Error: flake exports neither nixosConfigurations nor homeConfigurations."
            exit 1
          fi

          # NixOS systems
          if [[ -n "${HOSTS_RAW}" ]]; then
            readarray -t HOSTS <<< "${HOSTS_RAW}"
            echo "Discovered nixosConfigurations:"
            for h in "${HOSTS[@]}"; do echo "  - ${h}"; done

            for h in "${HOSTS[@]}"; do
              echo "::group::nixosConfigurations.${h}"
              out="$(nix build \
                --accept-flake-config \
                --no-link \
                --print-out-paths \
                ".#nixosConfigurations.${h}.config.system.build.toplevel")"

              # 1) Upload the full closure to Cachix
              push_closure "$out"

              # 2) Root only the latest locally (retention depth = 1)
              keep_latest_root "nixos-${h}" "$out"

              # 3) Keep on Cachix for 7 days (remote retention)
              cachix pin nixosconfig "nixos-${h}" "$out" --keep-days 7

              echo "::endgroup::"
            done
          else
            echo "No nixosConfigurations exported by flake."
          fi

          # Home Manager activations
          if [[ -n "${HOMES_RAW}" ]]; then
            readarray -t HOMES <<< "${HOMES_RAW}"
            echo "Discovered homeConfigurations:"
            for u in "${HOMES[@]}"; do echo "  - ${u}"; done

            for u in "${HOMES[@]}"; do
              echo "::group::homeConfigurations.${u}"
              out="$(nix build \
                --accept-flake-config \
                --no-link \
                --print-out-paths \
                ".#homeConfigurations.${u}.activationPackage")"

              # 1) Upload the full closure to Cachix
              push_closure "$out"

              # 2) Root only the latest locally (retention depth = 1)
              keep_latest_root "hm-${u}" "$out"

              # 3) Keep on Cachix for 7 days (remote retention)
              cachix pin nixosconfig "hm-${u}" "$out" --keep-days 7

              echo "::endgroup::"
            done
          else
            echo "No homeConfigurations exported by flake."
          fi

          # Local cleanup as the same user (no sudo): respects our per-user roots.
          nix-collect-garbage --delete-old || true
          nix-store --optimise || true
