---
creation_rules:
  # path should be relative to the location of this file (.sops.yaml)
  - path_regex: .*
    key_groups:
      - age:
          - age1y4sdqs8dnlrma395hjna6dmzcctaeqpr8rh0wx6ap626uv0mremqsgdn30 # Proxmox VM SSH key
          - age1wnxnwrzz506s9jw0hg5tptx7s4ujm7gja3wj5nerpll7cak4guxs4td3z0 # Proxmox VM and IGPU User Age Key
          - age1gr4papzzdqfxd34ushr88303f2ypdwvgx9cw2xqs87yn4zf8lpxqc0rur5 # Epi Key
          - age1d30ye2h5pm4y8fukm3hycsedln4hg6s9tmlmxernck8vfk2mdvnq99afq3 # Master Fleet Identity
          - age17pejn8m9tz063y3waahgyyn365n22hzgg5hr64ey7wk79ee8ccmsh8z294 # IGP
          - age1ysfdznu87vwwqtpudchkyx0wlhuhteqljrqkt6963pcmhwprlgcqasg0gv # Framework
          - &wsl age10hqxw3uxvg9nkc56rm495ty0rge0yhkcqp95gx00tgsv8ptg93mqwywlja # WSL
          - &dev age1tywfda7ms2v6jm22t3gvzjrck900k7ax460rg24z6unrtw7rzs6q44dyaj # dev
          - &sandbox age1zl8mt8gp43kyr02vz4scvvmlsl6929ps59tpcuutxazthxhsvueqvmfpyg # sandbox
          - &sandbox age1stg8x4ssjk2zn0qp3paltfdutkl77wfnph7mpastjlgw243gfycszl8mxt # sandbox
          - &cache age1cd4wnte9ffe65ysqzvtkwu5uzvvxn9xeln7n5ctkjsk4c589fc5qkt397e # cache
