---
creation_rules:
  # path should be relative to the location of this file (.sops.yaml)
  - path_regex: secrets/.*
    key_groups:
      - age:
          - age1y4sdqs8dnlrma395hjna6dmzcctaeqpr8rh0wx6ap626uv0mremqsgdn30 # Proxmox VM SSH key
          - age1wnxnwrzz506s9jw0hg5tptx7s4ujm7gja3wj5nerpll7cak4guxs4td3z0 # Proxmox VM and IGPU User Age Key
